// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XAnLK0nqwygtCuGMsIcWjrmlq8R9xYs',
    appId: '1:622560500483:web:fbc3e8cdb043c53584e736',
    messagingSenderId: '622560500483',
    projectId: 'notes-app-62ced',
    authDomain: 'notes-app-62ced.firebaseapp.com',
    storageBucket: 'notes-app-62ced.firebasestorage.app',
    measurementId: 'G-XGK5RDRVX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX6NpFYh9X_ELdtHTcH4Ap4PH96AVipD0',
    appId: '1:622560500483:android:70d276d816351f1984e736',
    messagingSenderId: '622560500483',
    projectId: 'notes-app-62ced',
    storageBucket: 'notes-app-62ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClf3a1vLSV6LfDeSZBUxGHR9vga1u3mC4',
    appId: '1:622560500483:ios:68dd8bf8f945f7bd84e736',
    messagingSenderId: '622560500483',
    projectId: 'notes-app-62ced',
    storageBucket: 'notes-app-62ced.firebasestorage.app',
    iosBundleId: 'com.example.noteeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClf3a1vLSV6LfDeSZBUxGHR9vga1u3mC4',
    appId: '1:622560500483:ios:68dd8bf8f945f7bd84e736',
    messagingSenderId: '622560500483',
    projectId: 'notes-app-62ced',
    storageBucket: 'notes-app-62ced.firebasestorage.app',
    iosBundleId: 'com.example.noteeApp',
  );
}
